### ISSUE TITLE
ecmwf: CDS API will be deprecated - 26. September 2024

### ISSUE THREAD

**Issue by maurerle** [NOWUM/open-energy-data-server#19]
The current CDS API will be removed at 
September 26, 2024 and will no longer be accessible from this date.

see:
https://confluence.ecmwf.int/display/CKB/Please+read%3A+CDS+and+ADS+migrating+to+new+infrastructure%3A+Common+Data+Store+%28CDS%29+Engine

**Comment by jsejdija** [comment]
For people who used the old cdspi and have an account there: you need to create a new ECMWF account, your old one wont work on https://cds-beta.climate.copernicus.eu/profile

Update your .cdsapi file according to https://cds-beta.climate.copernicus.eu/how-to-api 
Also make sure to update you cdsapi package: `pip install --upgrade cdsapi`

After that, the new version should just work.
